# Generated by Django 5.2.8 on 2025-11-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_add_postgres_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittrail",
            name="user_id",
            field=models.CharField(
                blank=True, db_column="user_id", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="user_name",
            field=models.CharField(
                blank=True, db_column="user_name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wastelog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wastelog",
            name="product_firebase_id",
            field=models.CharField(db_column="product_firebase_id", max_length=255),
        ),
        migrations.AlterField(
            model_name="wastelog",
            name="product_name",
            field=models.CharField(db_column="product_name", max_length=255),
        ),
        migrations.AlterField(
            model_name="wastelog",
            name="recorded_by",
            field=models.CharField(
                blank=True, db_column="recorded_by", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wastelog",
            name="waste_date",
            field=models.DateTimeField(db_column="waste_date"),
        ),
    ]
